// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBitan9G3LXR1DBc76KxaTuqsQW4p0KOtw',
    appId: '1:325737780316:web:3270c64477f2afe7118299',
    messagingSenderId: '325737780316',
    projectId: 'inventory-tracker-78488',
    authDomain: 'inventory-tracker-78488.firebaseapp.com',
    storageBucket: 'inventory-tracker-78488.firebasestorage.app',
    measurementId: 'G-E6NKDR7JX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPlL9wI9dmri8u9LNaLSjQ8oPfhL3Y_38',
    appId: '1:325737780316:android:1ecf51d84e5e0eaf118299',
    messagingSenderId: '325737780316',
    projectId: 'inventory-tracker-78488',
    storageBucket: 'inventory-tracker-78488.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuf8Zvw7qImmxJ9moTUJXo6AgSb96WwGM',
    appId: '1:325737780316:ios:a875645dc81b2936118299',
    messagingSenderId: '325737780316',
    projectId: 'inventory-tracker-78488',
    storageBucket: 'inventory-tracker-78488.firebasestorage.app',
    iosClientId: '325737780316-psolampc53dvnpf86o5kp82dbkjm8laa.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventoryTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuf8Zvw7qImmxJ9moTUJXo6AgSb96WwGM',
    appId: '1:325737780316:ios:a875645dc81b2936118299',
    messagingSenderId: '325737780316',
    projectId: 'inventory-tracker-78488',
    storageBucket: 'inventory-tracker-78488.firebasestorage.app',
    iosClientId: '325737780316-psolampc53dvnpf86o5kp82dbkjm8laa.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventoryTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBitan9G3LXR1DBc76KxaTuqsQW4p0KOtw',
    appId: '1:325737780316:web:153032f5b8407c57118299',
    messagingSenderId: '325737780316',
    projectId: 'inventory-tracker-78488',
    authDomain: 'inventory-tracker-78488.firebaseapp.com',
    storageBucket: 'inventory-tracker-78488.firebasestorage.app',
    measurementId: 'G-LTL3Q2MKBC',
  );
}
